language: node_js
node_js:
- "10.19.0"

install:
- npm install newman

before_script:
- node --version
- npm --version
- node_modules/.bin/newman --version

script:
- node_modules/.bin/newman run Google Books.postman_collection.json -d identifiants.json